// Source de données produits (TTC/jour)
// Images locales dans /public/outils, certains fichiers sans extension

export const products = [
  // Ordre et prix mis à jour selon les spécifications
  { slug: 'motobineuse-4-fraises-v2', name: 'Motobineuse 4 fraises', price: 50, unit: 'jour', image: '/outils/Motobineuse4fraises.jpg', desc: 'Largeur de travail 45 cm.', longDesc: 'Motobineuse thermique (à essence) 4 lames, 40 cm de large en fonction du modèle. Idéale pour surface allant jusqu\'à 100m2. Pratique et efficace pour retourner la terre afin d\'y faire un semi de gazon, un champ, une terrasse, un potager. Très simple d\'utilisation. Marche avant et arrière ce qui simplifie le travail, le bras est réglable pour une adaptation parfaite à votre taille et grâce au bras qui se replie, il est facile de le rentrer dans un véhicule.' },
  { slug: 'motobineuse-6-fraises', name: 'Motobineuse 6 fraises', price: 60, unit: 'jour', image: '/outils/Motobineuse6fraises.jpg', desc: 'Largeur de travail 80 cm.', longDesc: 'Motobineuse thermique (à essence) 6 lames, 85 cm de large en fonction du modèle. Idéale pour surface allant jusqu\'à 1000 m2. Pratique et efficace pour retourner la terre afin d\'y faire un semi de gazon, un champ, une terrasse, un potager. Très simple d\'utilisation. Marche avant et arrière ce qui simplifie le travail, le bras est réglable pour une adaptation parfaite à votre taille et grâce au bras qui se replie, il est facile de le rentrer dans un véhicule. Les lames peuvent s\'enlever facilement si besoin pour passer une porte ou un endroit étroit.' },
  { slug: 'rotovator', name: 'Rotovator', price: 100, unit: 'jour', image: '/outils/Rotovator.jpg', desc: 'Emiettage facile de la terre.', longDesc: 'Rotovator moteur briggs et stratton, idéal pour surface allant jusqu\'à 1500m2. Il est pratique et efficace pour retourner la terre afin d\'y faire un semi de gazon, un potager, un champ, une terrasse. Très puissant et permet donc d\'émietter sa terre (et ce dés le premier passage) jusque la rendre poudreuse.' },
  { slug: 'motoculteur', name: 'Motoculteur', price: 130, unit: 'jour', image: '/outils/Motoculteur', raw: true, desc: 'Travail du sol dans les champs ou prairies.', longDesc: 'Idéal pour labourer vos champs et très grands espaces car il faut de la place pour pouvoir le manier.' },
  { slug: 'rouleau-gazon', name: 'Rouleau à gazon', price: 10, unit: 'jour', image: '/outils/Rouleaugazon.jpg', desc: 'Tassement du sol.', longDesc: 'Rouleau à gazon pour tasser la terre, le sol.' },
  { slug: 'epandeur', name: 'Epandeur Semoir', price: 10, unit: 'jour', image: '/outils/Epandeur.jpg', desc: 'Épandage d\'engrais et semences.', longDesc: 'Idéal pour semer vos graines de gazon ou de l\'engrais. Le réglage de l\'intensité de semi se fait facilement.' },
  { slug: 'rogneuse-souche', name: 'Rogneuse de souche', price: 200, unit: 'jour', image: '/outils/Rogneusedesouche.jpg', desc: 'Rognage des souches sous le sol.', longDesc: 'Contrairement au dessouchage par pelleteuse ou au tracteur, la dessoucheuse grignoteuse de souche est le moyen le plus sûr et le plus économique d\'éliminer les racines et les souches. Elle a le grand avantage d\'éliminer vos veilles souches sans endommager votre propriété. Elle est equipée d\'un moteur puissant de 15 cv et offre de très bons résultats.' },
  { slug: 'debroussailleuse', name: 'Débroussailleuse', price: 30, unit: 'jour', image: '/outils/Debroussailleuse.jpg', desc: 'Débroussaillage et entretien terrain.', longDesc: 'Que vous soyez confronté à des herbes hautes, des broussailles ou des terrains devenus difficiles d\'accès, cet équipement vous permettra de venir à bout des végétations les plus récalcitrantes. Débroussailleuse thermique équipée d\'une tête à fil ou d\'une lame (à votre convenance) et d\'un harnais pour vous simplifier la vie.' },
  { slug: 'taille-haie-thermique', name: 'Taille haie', price: 30, unit: 'jour', image: '/outils/Taillehaiethermique', raw: true, desc: 'Entretien des haies.', longDesc: 'Taille haie thermique avec lamier double tranchant, idéal pour la taille de haie à hauteur d\'homme.' },
  { slug: 'taille-haie-perche', name: 'Taille haie perche', price: 70, unit: 'jour', image: '/outils/taillehaieperche.jpg', desc: 'Taille des hautes haies.', longDesc: 'Taille haie Stihl thermique à perche. Idéal pour tailler vos haies en hauteur.' },
  { slug: 'elagueuse-perche', name: 'Élagueuse perche', price: 80, unit: 'jour', image: '/outils/Elagueuseperche.jpg', desc: 'Élagage en hauteur.', longDesc: 'Tronconneuse élagueuse Stihl thermique à perche. Idéale pour couper vos petites branches en hauteur.' },
  { slug: 'tariere', name: 'Tarière', price: 50, unit: 'jour', image: '/outils/Tariere.jpg', desc: 'Perçage des trous pour plantations ou poteaux.', longDesc: 'Tarrière thermique Stihl, elle vous facilitera la vie pour faire vos trous pour le jardinage et fin d\'accueillir vos plantations ou dans vos travaux de maçonnerie pour faire des poteaux. Fournie avec 3 mèches (100, 200 et 300 mm). Elle est équipée d\'un puissant moteur 4-MIX 2 temps avec réservoir de carburant agrandi, cadre avec poignées anti-vibrations, d\'un large rembourrage d\'appui offrant un grand confort d\'utilisation et d\'un frein de mèche quickstop (c\'est une sécurité) qui lui permet de s\'arrêter immédiatement si l\'on perd le contrôle. Ce matériel est prévu pour travailler sur de la terre meuble, sans pierres et sans racines.' },
  { slug: 'arrache-souche', name: 'Arrache souche', price: 50, unit: 'jour', image: '/outils/Arrachesouche.jpg', desc: 'Extraction de souches d\'arbres.', longDesc: 'Idéal pour dessoucher vos haies de thuyas, laurier palmes, cerisier, pommier, ou petits arbres et troncs jusqu\'à +/- 20 à 25 cm de diamètre. Le matériel est composé d\'une platine en acier renforcé, de 3 étais réglables, d\'un palan à chaîne 3 tonnes de qualité et d\'élingue (sangle). Fourni avec plusieurs sangles qui s\'adapteront à tous les types de tronc que vous aurez. Le tout est transportable dans une voiture.' },
  { slug: 'tronconneuse-thermique', name: 'Tronçonneuse', price: 70, unit: 'jour', image: '/outils/TronçonneusesThermiques', raw: true, desc: 'Abattage, élagage et coupe de bois.', longDesc: 'Tronçonneuse thermique (à essence). -Tronçonneuse stihl guide de 35cm, 60€ la journée -Tronçonneuse stihl guide de 40cm, 70€ la journée. Fourni avec le plein de mélange et d\'huile de chaîne. Toutes les tronçonneuses sont de marque Stihl avec chaîne neuve ou affûtée et entretenue après chaque utilisation.' },
  { slug: 'tondeuse-gazon', name: 'Tondeuse à gazon', price: 40, unit: 'jour', image: '/outils/Tondeuseagazon.jpg', desc: 'Tonte de pelouse, espaces verts.', longDesc: 'Tondeuse à gazon thermique autotractée. Puissante et résistante, vous apprécierez sa maniabilité. Conçue pour des surfaces allant jusqu\'à 1500m. Largeur de coupe 46cm, bac de ramassage 60L, plusieurs niveaux de réglages de coupe.' },
  { slug: 'decoupeuse-beton', name: 'Découpeuse béton', price: 50, unit: 'jour', image: '/outils/Découpeusebéton', raw: true, desc: 'Découpe de béton et matériaux durs.', longDesc: 'Tronçonneuse scie à disque / disqueuse / découpeuse de sol diamant thermique Husqvarna K770. Machine puissante et polyvalente. Ses performances seront impeccables pour la découpe des murs et des sols (béton, asphalte, pavé, dalle, bitume, parpaing, agglo, brique). Équipée d\'un branchement pour un tuyau d\'eau afin de limiter la poussière. L\'usure du disque sera facturée en supplément (cela dépendra de toutes les coupes que vous aurez à faire).' },
  { slug: 'marteau-piqueur', name: 'Marteau piqueur', price: 50, unit: 'jour', image: '/outils/MarteauPiqueur', raw: true, desc: 'Démolition et burinage intensifs des sols.', longDesc: 'Marteau piqueur, brise béton Hilti Te 2000 conçu pour le travail de démolition des sols, fourni avec 2 burins (1 pointu et 1 plat). Grâce au système de réduction active des vibrations (AVR), l\'outil est moins fatiguant à utiliser, du coup la fatigue ne se fait pas ressentir et le travail est plus agréable. Démolir du béton n\'aura jamais été si simple. Facile à transporter car fourni avec son chariot.' },
  { slug: 'marteau-piqueur-burineur-hilti', name: 'Marteau piqueur Burineur HILTI TE 800', price: 50, unit: 'jour', image: '/outils/marteau-piqueur-burineur.jpg', desc: 'Démolition lourde de vos murs.', longDesc: 'Ce marteau piqueur burineur brise béton est le meilleur pour la démolition lourde de vos murs. Il permet de casser du béton dur ou des murs porteurs avec plus d\'efficacité et moins d\'effort. Fourni avec 2 burins (1 pointu et 1 plat). Le TE-800-AVR est clairement le plus adapté pour démolir un mur solide ou faire des ouvertures importantes dans du béton. Grâce au système de réduction active des vibrations (AVR), l\'outil est moins fatiguant à utiliser, du coup la fatigue ne se fait pas ressentir et le travail est plus agréable. Démolir du béton n\'aura jamais été si simple. Facile à transporter car fourni avec sa malette de transport.' },
  { slug: 'plaque-vibrante', name: 'Plaque vibrante Dameuse', price: 60, unit: 'jour', image: '/outils/Plaquevibrantedameuse.jpg', desc: 'Compactage de sols et surfaces planes.', longDesc: 'Plaque vibrante Dameuse thermique (à essence) de marque Ammann reconnue pour être fiable et robuste. Idéale pour tasser ou compacter vos terrains, terrasses, jardins ou pour de l\'enrobé. Elle est équipée de roues ce qui facilite le transport et le bras peut se replier.' },
  { slug: 'pilonneuse', name: 'Pilonneuse', price: 60, unit: 'jour', image: '/outils/Pilonneuse', raw: true, desc: 'Compactage de sols et tranchées.', longDesc: 'La piloneuse Bomag bt 65 est la plus puissante de sa catégorie, elle est dédiée au gros œuvre et offre le meilleur compactage. Elle convient parfaitement aux travaux dans les tranchées et les canalisations, l\'aménagement des espaces verts, le compactage des remblais, les fondations, les retouches et les réparations. Elle est équipée de roues ce qui facilite le transport.' },
  { slug: 'betonniere', name: 'Bétonnière', price: 35, unit: 'jour', image: '/outils/Betonniere', raw: true, desc: 'Permet de malaxer le béton ou le mortier.', longDesc: 'Bétonnière compacte 160L, cuve acier, moteur fiable. Parfaite pour chantiers de petite et moyenne taille. Nettoyage simple et entretien facile.' },
  { slug: 'ponceuse-girafe', name: 'Ponceuse girafe', price: 30, unit: 'jour', image: '/outils/Ponceusegirafe.jpg', desc: 'Ponçage placo murs et plafonds.', longDesc: 'Conçue pour le ponçage d\'enduit, cette ponceuse girafe à perche vous facilitera la tâche. Elle a le réglage de la vitesse et se branche à une prise normale. Si vous avez un aspirateur pour pourrez le brancher dessus (une arrivée est prévue pour) afin d\'éviter de faire trop de poussière. Disque de ponçage non fourni mais je vous dirais lequel modèle acheter (très facile à trouver en magasin de bricolage).' },
  { slug: 'carrelette', name: 'Carrelette', price: 25, unit: 'jour', image: '/outils/Carrelette', raw: true, desc: 'Coupe précise de carrelage.', longDesc: 'Carrelette manuelle pour carreaux céramique et grès. Butée précise, coupe nette et propre pour vos travaux de pose de carrelage.' },
  { slug: 'rainureuse', name: 'Rainureuse', price: 30, unit: 'jour', image: '/outils/Rainureuse.jpg', desc: 'Saignées pour gaines électriques.', longDesc: 'Rainureuse à béton, disques diamètre 125 mm. Dimension de rainurage maxi: 30 mm de large x 30 mm de profond. Puissance 1400W, se branche à une prise normale. Fournie avec disque diamant pour placo, brique, béton. Si vous avez un aspirateur pour pourrez le brancher dessus (une arrivée est prévue pour) afin d\'éviter de faire trop de poussière.' },
  { slug: 'malaxeur', name: 'Malaxeur', price: 20, unit: 'jour', image: '/outils/Malaxeur', raw: true, desc: 'Préparation d\'enduits, mortiers, peintures.', longDesc: 'Malaxeur électrique à variateur, poignée ergonomique. Pour un mélange homogène de vos enduits, mortiers-colles et peintures épaisses.' },
  { slug: 'perceuse', name: 'Perceuse', price: 20, unit: 'jour', image: '/outils/Perceuse', raw: true, desc: 'Perçage polyvalent, bois/métal/béton.', longDesc: 'Perceuse à percussion 750W, mandarin autoserrant. Pour le perçage du bois, métal et maçonnerie légère.' },
  { slug: 'karcher', name: 'Karcher', price: 30, unit: 'jour', image: '/outils/Karcher.jpg', desc: 'Nettoyage à haute pression.', longDesc: 'Nettoyeur haute pression pour terrasses, façades et véhicules. Puissant et efficace pour tous vos travaux de nettoyage.' }
];

export function getProductBySlug(slug){
  return products.find(p => p.slug === slug);
}

export function formatPriceTTC(price){
  return `${price.toFixed(2)}€`;
}
